### ISSUE TITLE
Error importing module

### ISSUE THREAD

**Issue by zeljko-bulatovic** [ueberdosis/hocuspocus-issues#1]
Hi,

I am not sure if this is related to hocuspucus server, or to my config, but when i followed tutorial, i am not able to run my server, because of the added import. 

I am receiving the following error:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: .../node_modules/@hocuspocus/server/dist/hocuspocus-server.js
require() of ES modules is not supported.

I am using Babel for build..

Update:

I found that this issue is related to the node version:
https://github.com/manuelbieh/geolib/issues/208

After switching to node version 12.12.0, now i got error from your module:

import WebSocket from 'ws';
^^^^^^

SyntaxError: Cannot use import statement outside a module
....
....

**Comment by hanspagel** [comment]
Oh, we’ve developed under Node 15. It’s not compatible with older versions, at least for now.

Any chance you could try Node 15?

**Comment by zeljko-bulatovic** [comment]
Huh, i will try to update my project to node 15 first. Thank you for answer!

**Comment by zeljko-bulatovic** [comment]
Thank you for forcing me to update the project to the latest node :) It is working now :)
