### ISSUE TITLE
Exception on front-end when trying to update doc

### ISSUE THREAD

**Issue by zeljko-bulatovic** [ueberdosis/hocuspocus-issues#2]
I followed tutorial and done minimal setup, just to make it work, but i am receiving an exception on the front-end.

So, when i return document from onCreateDocument(data) on server side, i am receiving this error on front end:

```
Exception: 
TypeError: Cannot read property 'matchesNode' of null at EditorView.updateStateInner (webpack-internal:///./node_modules/prosemirror-view/dist/index.es.js:4765:43) at EditorView.updateState (webpack-internal:///./node_modules/prosemirror-view/dist/index.es.js:4736:8) at Editor.dispatchTransaction (webpack-internal:///./node_modules/@tiptap/core/dist/tiptap-core.esm.js:2407:19) at EditorView.dispatch (webpack-internal:///./node_modules/prosemirror-view/dist/index.es.js:5004:50) at eval (webpack-internal:///./node_modules/y-prosemirror/src/plugins/sync-plugin.js:301:28) at ProsemirrorBinding.eval [as mux] (webpack-internal:///./node_modules/lib0/mutex.js:37:9) at ProsemirrorBinding._forceRerender (webpack-internal:///./node_modules/y-prosemirror/src/plugins/sync-plugin.js:297:10) at eval (webpack-internal:///./node_modules/y-prosemirror/src/plugins/sync-plugin.js:156:17)
message: "Cannot read property 'matchesNode' of null"
```

Hocuspocus setup method:

```
async onCreateDocument(data) {
	try {
		const prosemirrorDocument = JSON.parse(
			`{
				"type": "doc",
				"content": [{ "type": "paragraph", "content": [] }]
			}`
		);

		// When using the tiptap editor we need the schema to create
		// a prosemirror JSON. You can use the `getSchema` method and
		// pass it all the tiptap extensions you're using in the frontend
		const schema = getSchema([ Document, Paragraph, Text ]);

		// Convert the prosemirror JSON to a Y-Doc and simply return it
		const result = prosemirrorJSONToYDoc(schema, prosemirrorDocument);
		return result;
		// return data.document;
	} catch(e) {
		console.log(e);
	}
}
```

This is front-end setup:

```
mounted() {
    const ydoc = new Y.Doc();
    this.provider = new WebsocketProvider(process.env.VUE_APP_WS_ENDPOINT, 'tiptap-collaboration-example', ydoc);
    this.provider.on('status', event => {
      this.status = event.status;
    });

   this.editor = new Editor({
      extensions: [
	Document,
        Paragraph,
        Text,
	CollaborationCursor.configure({
          provider: this.provider,
          user: this.currentUser,
          onUpdate: users => {
            this.users = users;
          },
        }),
        Collaboration.configure({ document: ydoc }),
	],
	});

			this.updateCurrentUser({
				name: this.getRandomName(),
				color: this.getRandomColor()
			});

		localStorage.setItem('currentUser', JSON.stringify(this.currentUser));
	},
```

Those are the library versions that i am using on the front-end:
```
"@tiptap/vue-2": "^2.0.0-beta.1",
"@tiptap/starter-kit": "^2.0.0-beta.3",
"@tiptap/core": "^2.0.0-beta.2",
"@tiptap/extension-underline": "^2.0.0-beta.1",
"@tiptap/extension-image": "^2.0.0-beta.1",
"prosemirror-commands": "^1.1.7",
"@tiptap/extension-collaboration": "^2.0.0-beta.3",
"@tiptap/extension-collaboration-cursor": "^2.0.0-beta.3",
"yjs": "^13.5.2",
"y-websocket": "^1.3.11"
```

Any thoughts what am i doing wrong?

**Comment by hanspagel** [comment]
Oh no! Looks good on the first glance. 

Just a quick note, you don’t have to `onCreateDocument` to get it just working. This hook is needed if you want to have full control over the storage of your documents. 

Did you get the quickstart example to work? That should be enough get it working: 

```js
import { Server } from '@hocuspocus/server'

Server.listen({
   port: '1234'
})
```

**Comment by zeljko-bulatovic** [comment]
Yes, i made it work using simple implementation but without storing documents anywhere. 
I need full control, since i want to store and retrieve document from database.

Also, i am little bit confused when trying to move from v1 to v2. 

At the moment, i have working collaboration using TipTap v1 and Socket.io library on front and backend, which is working fine. 

I have few questions now when i am moving to v2:
1. Can we use the way how old Collaboration extension from v1 worked (to send updates manually and updating doc when receiving data from WebSocket)? Or we must use this new one, which is only working with YJS document as far as i see?
2. Can we use SocketIO library with new collaboration (i have fully working front and back-ends, so thinking about reusing as much as possible)

Any specific tutorial / code example which you want me to try with use case to store data in file / database, that you think it should work?

Thank you!

**Comment by hanspagel** [comment]
The old collaborative editing system should still work, but we don’t plan to port the extensions. We’ve had this in production and had so much trouble with it. Y.js is way more robust and better in many ways.

I want to get this working for you. Sorry for all the bumps. :-)

I’ve set up a test project, see the complete code below. It doesn’t throw the exception you’re describing, but I don’t see the content in the editor though. I’ll look into this.

```js
import { Server } from '@hocuspocus/server'
import { Logger } from '@hocuspocus/logger'

import { getSchema } from '@tiptap/core'
import { Document } from '@tiptap/extension-document'
import { Paragraph } from '@tiptap/extension-paragraph'
import { Text } from '@tiptap/extension-text'

import { prosemirrorJSONToYDoc } from 'y-prosemirror'

const server = Server.configure({
  async onCreateDocument(data) {
    const prosemirrorDocument = {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Example Text',
            }
          ]
        }
      ]
    }

    const schema = getSchema([Document, Paragraph, Text])
    const ydoc = prosemirrorJSONToYDoc(schema, prosemirrorDocument, 'default')

    console.log('onCreateDocument', ydoc.toJSON())

    return ydoc
  },

  extensions: [
    new Logger,
  ],
})

server.listen()
```

**Comment by hanspagel** [comment]
In the version I’ve installed there is not even a `onCreateDocument` in the code. I think we’ll need to publish a new release. 👀

**Comment by zeljko-bulatovic** [comment]
Hi Hans, any updates? Thank you in advance!

**Comment by kriskbx** [comment]
Hey Zeljko! Unfortunately, I'm not able to reproduce your issue. What Node.js version are you using? Can you upgrade `@hocuspocus/server` to version `1.0.0-alpha.37` and try again? Do you get a different error message now?

**Comment by kriskbx** [comment]
Can you alter this line in your `onCreateDocument` method and add a third parameter `'default'`?
This is the name of the Yjs shared type the actual document will be stored in. Tiptaps collaboration extension calls this [field](https://next.tiptap.dev/api/extensions/collaboration#settings) and it defaults to "default". The default of `prosemirrorJSONToYDoc()` is "prosemirror". This could be the issue.

```typescript
const result = prosemirrorJSONToYDoc(schema, prosemirrorDocument, 'default');
```

**Comment by kriskbx** [comment]
Sorry for the bumps. Hocuspocus and the docs are pretty much still in an early alpha stage. :)

**Comment by zeljko-bulatovic** [comment]
Hi, I can't install ^1.0.0-alpha.37 at the moment. I am receiving this error at the moment:
npm WARN registry Using stale data from https://registry.ueber.io/ due to a request error during revalidation.

Also, when i navigate to:
https://store.ueber.io/purchases

It shows 500 internal server error. Maybe those two are connected somehow..

**Comment by hanspagel** [comment]
Would you mind to try again? The store and registry seem to run again. Thanks for going through those bumps with us!

**Comment by zeljko-bulatovic** [comment]
Just tried again, and i got the following error:
`npm ERR! notarget No matching version found for @hocuspocus/server@^1.0.0-alpha.37.`

 Also, it seems that store is not working again.

**Comment by kriskbx** [comment]
Can you try again, please?

**Comment by zeljko-bulatovic** [comment]
Still the same:
npm WARN registry Using stale data from https://registry.ueber.io/ due to a request error during revalidation.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @hocuspocus/server@^1.0.0-alpha.37.

And https://store.ueber.io/purchases is still showing 500 server error screen.

**Comment by zeljko-bulatovic** [comment]
Hey guys, i just tried and saw that you fixed the store page. It looks like that my auth token is now changed, and after npmrc update with the new token, I was able to download alpha.37 version! I will let you know how it is working..

**Comment by zeljko-bulatovic** [comment]
Just to inform you, this will take some time, since i need to upgrade project to use type="module" in my package.json, in order to import hocuspocus server, and to get rid of some require() imports. Also, i need to upgrade project to node v15.. so it is not 5 minutes of work :)

**Comment by kriskbx** [comment]
Sorry, I didn't find the time to test the store page yet and that's why I didn't write you an answer here. Glad it works now!
No worries, take your time. :)

**Comment by kriskbx** [comment]
FYI: If you used any extension - for example the RocksDB extension - you need to update your `package.json`. We just renamed all extensions. `@hocuspocus/rocksdb` is now called `@hocuspocus/extension-rocksdb` and `@hocuspocus/logger` is now called `@hocuspocus/extension-logger`.

**Comment by zeljko-bulatovic** [comment]
Hi guys, here is the update! 

I finally managed to do it, but i spotted one more issue. If the server is running and i refresh the editor page, i got infinite loop of front-end trying to connect to the websocket. If i run front end first and then start the server, everything is working fine. Here is the screenshot of the network tab.

<img width="782" alt="Requests" src="https://user-images.githubusercontent.com/17200131/112763042-22517f00-9003-11eb-9ec3-642b96db4db3.png">

Here is the front-end code:
<img width="1328" alt="FrontEnd" src="https://user-images.githubusercontent.com/17200131/112763133-72c8dc80-9003-11eb-87b1-1657c21affb6.png">

Thank you in advance for the help!

**Comment by kriskbx** [comment]
Try to set `throttle` in your Server config to false:

```javascript
const server = Server.configure({
  throttle: false,
})
```

Hocuspocus throttles connection-attempts by default when passing a threshold of 5 per minute from the same ip-address. I will increase that in the next release. It is meant to prevent people from flooding your server with connection-attempts, as the client will currently not stop trying to reconnect and thus kind of DDoSes your server. :D

**Comment by zeljko-bulatovic** [comment]
It is working now, thank you! :)

**Comment by kriskbx** [comment]
Awesome, congrats! We're always happy to help. :)
