### ISSUE TITLE
Document name from context?

### ISSUE THREAD

**Issue by flaviouk** [ueberdosis/hocuspocus-issues#4]
Hi,

Would it be possible to get the documentName from context and default to parsing the request URL if none is provided? This would help when integrating with express for example

```js
const hookPayload = {
    documentName: context?.documentName || Hocuspocus.getDocumentName(request),
    requestHeaders: request.headers,
    requestParameters: Hocuspocus.getParameters(request),
    socketId,
}
```

**Comment by kriskbx** [comment]
Hej Flávio.

Thanks a lot for your suggestion. I think it would be better to move the logic to get the document name into the `listen()` method itself and add a `documentName` parameter to `handleConnection()`.

```typescript
handleConnection(incoming: WebSocket, request: IncomingMessage, documentName: string, context: any = null): void
```

Using context for this feels kinda hacky and we are still on alpha, so changing the API is not a big deal for me. What do you think?

**Comment by flaviouk** [comment]
Heya! Yeah sounds good, just need a way to pass this in, ideally the fewer arguments we have the better, but 4 is not too bad

**Comment by kriskbx** [comment]
Cool. Will include it in the next release and drop you a line here when it's published. ;)

**Comment by kriskbx** [comment]
I just published `@hocuspocus/server@1.0.0-alpha.44` which includes this change. I also updated the documentation on the integration of express: https://www.hocuspocus.dev/guide/framework-integration/#express

Let me know, if you need more help! :)

**Comment by flaviouk** [comment]
Thanks @kriskbx, tried installing but it's not working:
error Couldn't find package "@hocuspocus/server@1.0.0-alpha.44"

**Comment by kriskbx** [comment]
Try putting it in your `package.json` and run `yarn update` or `npm update`:

```json
{
    "dependencies": {
        "@hocuspocus/server": "^1.0.0-alpha.44"
    }
}
```

**Comment by flaviouk** [comment]
Oops my bad, I had made some changes on the project structure, and forgot to move the .npmrc, works perfectly thanks!
