### ISSUE TITLE
How to reconnect my losing connection?

### ISSUE THREAD

**Issue by DenysPoliarush** [ueberdosis/hocuspocus-issues#5]
Hi guys! Thanks for your work!

I have set up a hocusfocus server in my application and it works well. But I have one problem. Socket connection never reconnects.

I opened your sample site and left it open for 2 days, after I came back I can still write something. That's cool. On the network tab, I can see how some socket connections were closed and one is always open.

In my application, I cannot do this. My socket connection always closes after some time of inactivity and never creates a new connection. How can I fix this?  

<img width="610" alt="Screenshot 2021-04-12 at 17 36 53" src="https://user-images.githubusercontent.com/66991536/114416142-0e884a00-9bb9-11eb-9552-fdd2bfc93517.png">
<img width="802" alt="Screenshot 2021-04-12 at 18 00 38" src="https://user-images.githubusercontent.com/66991536/114416149-0fb97700-9bb9-11eb-822c-93a55dbbec77.png">

My server code
```
const server = Server.configure({
  async onCreateDocument (data) {
    const fieldName = 'default';

    if (data.document.isEmpty(fieldName)) {
      return;
    }

    const project = await ProjectService.getById({
      id: data.context.projectId,
      userId: data.context.userId
    });

    let prosemirrorJSON = project.document;

    if (!prosemirrorJSON) {
      const { document } = (new JSDOM(project.body.trim())).window;

      const schema = getSchema(extensions);

      prosemirrorJSON = DOMParser
        .fromSchema(schema)
        .parse(document, { preserveWhitespace: true })
        .toJSON();
    }

    return TiptapTransformer.toYdoc(prosemirrorJSON, extensions, fieldName);
  },

  async onConnect (data) {
    const { requestParameters } = data;

    const token = requestParameters.get('token');

    const user = await UserService.getUserByToken(token);
    return {
      userId: user.id,
      token: token
    };
  },

  async onChange (data) {
    if (data.context.ws) {
      try {
        await CollaborationService.checkPermission({
          token: data.context.token,
          ws: data.context.ws
        });
      } catch (error) {
        data.context.ws.close(4000, error.Error);
        return;
      }
    }

    const save = async () => {
      const prosemirrorJSON = TiptapTransformer.fromYdoc(data.document, 'default');

      try {
        await ProjectService.update({
          id: data.context.projectId,
          userId: data.context.userId,
          document: prosemirrorJSON
        });
      } catch (error) {
        data.context.ws.close(4000, error.Error);
      }
    };

    debounced?.clear();
    debounced = debounce(() => save(), 1000);
    debounced();
  },

  timeout: 8640000 // 24hour
});


router.get('/:projectId', async ctx => {
  const projectId = parseInt(ctx.params.projectId);

  try {
    if (ctx.ws) {
      const ws = await ctx.ws();

      const context = {
        projectId: projectId,
        ws
      };

      server.handleConnection(ws, ctx.request, context);
    }
  } catch (err) {
    ctx.bad(400, err);
  }
});

```

Thanks for your help in advance!

**Comment by kriskbx** [comment]
Hey 👋

My first guess is that it's somehow related to throttling?! We are currently working on moving this feature out of the core into its own extension. Until this happened you could try to completely disable it by passing `throttle: false` to the configuration method: https://www.hocuspocus.dev/guide/configuration#throttling 

If that doesn't work, we need more information. Install the logger extension to get some output on what's going on the server side and post it here, please. You can find the instructions on how to install and use it here: https://www.hocuspocus.dev/extensions/logger

**Comment by DenysPoliarush** [comment]
Thank you for such a quick response.

I set `throttle: false` but that didn't help. 

Then I installed the logger, but it didn't show me anything either. In the server console, I see only this
[2021-04-12T20:10:20.451] [INFO] access - GET /myApi/668?token=some_toke&projectId=668 404 1,202s -
[2021-04-12T20:10:20.452Z] Connection to "api/collaborations/668" closed … 

Maybe there is nothing to do with hocuspocus and I need to find errors in my code?

**Comment by kriskbx** [comment]
I think so. A few notes about your implementation:

1. In your `onChange` method you check if the current user has the permission to change the document and close the connection there if not. Don't ever do this. Don't close connections manually, this will break things. Besides that `onChange` will be triggered when changes are already synced to other clients. (We will probably change that in the near future) You should **always** use `onConnect` to do authorization and authentication and throw an empty exception or reject the returned Promise if not authorized. Please refer to the guide as it gives you examples on how to do that.
2. The `handleConnection` method is not used correctly. It expects the `documentName: string` as the third argument. And don't pass the `projectId` through your context. Use the concept of documentName as the rest of hocuspocus relies on it.
3. This is not good: `timeout: 8640000 // 24hour`. WebSocket connections tempt to be terminated without the server recognizing it. This is why people implement a ping-pong mechanic so unresponsive connections time out. Set this to something reasonable like 10-60 seconds.

**Comment by DenysPoliarush** [comment]
Hi @kriskbx! Thanks for your advices. I removed checking user permissions on change method. Also i removed timeout, so now it should be 30seconds as default. But these updates didn't fixed my problem. Could you please tell me how I can implement pong pong mechanic? Do I need implement it on the frontend or your extension collaboration should do it by self?

**Comment by DenysPoliarush** [comment]
I added this code to my frontend and I got the error described in issue #3. 

```
function connect () {
  provider = new WebsocketProvider(
    process.env.VUE_APP_WEBSOCKET_URL,
    'my-document',
    ydoc
  )

  provider.ws.onclose = (e) => {
    setTimeout(function () {
      connect()
    }, 1000)
  }
}

connect()
```

Then I added `RocksDB extension` and now it seems to be working fine. 

Is this the right approach? Thanks!

**Comment by kriskbx** [comment]
> Could you please tell me how I can implement pong pong mechanic? Do I need implement it on the frontend or your extension collaboration should do it by self?

You don't need to. hocuspocus is doing this for you, this is what the `timeout` parameter is configuring. Just set it to something reasonable like 10-60 seconds and it should be fine.

```javascript
  provider.ws.onclose = (e) => {
    setTimeout(function () {
      connect()
    }, 1000)
  }
```

Don't do this! y-websocket will reconnect on its own. This will potentially break things. Please follow the guide on "Collaborative Editing" in the tiptap docs.

> Then I added RocksDB extension and now it seems to be working fine. Is this the right approach?

Yes, you should always use the RocksDB extension: https://www.hocuspocus.dev/guide/documents#using-a-primary-storage

I'm closing this for now. Feel free to reopen it if you still encounter issues.

**Comment by DenysPoliarush** [comment]
Unfortunately, it doesn't work for me yet. I've already set up timeout=30000(30 seconds) but this doesn't help. It's never reconnected by self. 

Could there be a problem with the websocket connection and koa?
Do you have an example of how this connects with koa?

**Comment by DenysPoliarush** [comment]
And could you tell me what the minimum software requirements should be. Thanks!
